/* Generated by MyraPad at 12/15/2024 8:25:47 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace DigitalRise.Editor.UI
{
	partial class AddNewItemDialog: Dialog
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Item 1";

			var radioButton1 = new RadioButton();
			radioButton1.Content = label1;

			var label2 = new Label();
			label2.Text = "Item 2";

			var radioButton2 = new RadioButton();
			radioButton2.Content = label2;

			var label3 = new Label();
			label3.Text = "Item 3";

			var radioButton3 = new RadioButton();
			radioButton3.Content = label3;

			_itemsPanel = new VerticalStackPanel();
			_itemsPanel.Spacing = 4;
			_itemsPanel.Id = "_itemsPanel";
			_itemsPanel.Widgets.Add(radioButton1);
			_itemsPanel.Widgets.Add(radioButton2);
			_itemsPanel.Widgets.Add(radioButton3);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(_itemsPanel);

			
			Title = "Add New Scene";
			Left = 614;
			Top = 260;
			Width = 300;
			Content = verticalStackPanel1;
		}

		
		public VerticalStackPanel _itemsPanel;
	}
}
