/* Generated by MyraPad at 12/14/2024 11:56:40 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace DigitalRise.Editor.UI
{
	partial class EditMaterialsDialog: Dialog
	{
		private void BuildUI()
		{
			var horizontalSeparator1 = new HorizontalSeparator();

			_listMaterials = new ListView();
			_listMaterials.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_listMaterials.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_listMaterials.Id = "_listMaterials";

			_properties = new PropertyGrid();
			_properties.Id = "_properties";

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.Content = _properties;

			var horizontalSplitPane1 = new HorizontalSplitPane();
			StackPanel.SetProportionType(horizontalSplitPane1, Myra.Graphics2D.UI.ProportionType.Fill);
			horizontalSplitPane1.Widgets.Add(_listMaterials);
			horizontalSplitPane1.Widgets.Add(scrollViewer1);

			var horizontalSeparator2 = new HorizontalSeparator();

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(horizontalSplitPane1);
			verticalStackPanel1.Widgets.Add(horizontalSeparator2);

			
			Title = "Edit Materials";
			Left = 414;
			Top = 78;
			Width = 700;
			Height = 500;
			Content = verticalStackPanel1;
		}

		
		public ListView _listMaterials;
		public PropertyGrid _properties;
	}
}
