/* Generated by MyraPad at 12/4/2024 9:52:59 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace DigitalRise.Editor.UI
{
	partial class EditMaterialsDialog: Dialog
	{
		private void BuildUI()
		{
			var horizontalSeparator1 = new HorizontalSeparator();

			_panelLeft = new Panel();
			_panelLeft.Id = "_panelLeft";

			_properties = new PropertyGrid();
			_properties.Id = "_properties";

			var scrollViewer1 = new ScrollViewer();
			scrollViewer1.Content = _properties;

			var horizontalSplitPane1 = new HorizontalSplitPane();
			StackPanel.SetProportionType(horizontalSplitPane1, Myra.Graphics2D.UI.ProportionType.Fill);
			horizontalSplitPane1.Widgets.Add(_panelLeft);
			horizontalSplitPane1.Widgets.Add(scrollViewer1);

			var horizontalSeparator2 = new HorizontalSeparator();

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Widgets.Add(horizontalSeparator1);
			verticalStackPanel1.Widgets.Add(horizontalSplitPane1);
			verticalStackPanel1.Widgets.Add(horizontalSeparator2);

			
			Title = "Edit Materials";
			Left = 531;
			Top = 78;
			Width = 500;
			Height = 500;
			Content = verticalStackPanel1;
		}

		
		public Panel _panelLeft;
		public PropertyGrid _properties;
	}
}
