/* Generated by MyraPad at 12/30/2024 7:25:05 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace DigitalRise.Editor.UI
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			_menuItemOpenFolder = new MenuItem();
			_menuItemOpenFolder.Text = "&Open Folder";
			_menuItemOpenFolder.Id = "_menuItemOpenFolder";

			_menuItemSaveCurrentItem = new MenuItem();
			_menuItemSaveCurrentItem.Text = "&Save Current Item";
			_menuItemSaveCurrentItem.ShortcutText = "Ctrl+S";
			_menuItemSaveCurrentItem.Id = "_menuItemSaveCurrentItem";

			_menuItemSaveEverything = new MenuItem();
			_menuItemSaveEverything.Text = "Save &Everything";
			_menuItemSaveEverything.Id = "_menuItemSaveEverything";

			var menuSeparator1 = new MenuSeparator();

			_menuItemNewPrefab = new MenuItem();
			_menuItemNewPrefab.Text = "&New Prefab";
			_menuItemNewPrefab.Id = "_menuItemNewPrefab";

			_menuItemNewScene = new MenuItem();
			_menuItemNewScene.Text = "New &Scene";
			_menuItemNewScene.Id = "_menuItemNewScene";

			var menuSeparator2 = new MenuSeparator();

			_menuItemReload = new MenuItem();
			_menuItemReload.Text = "&Reload";
			_menuItemReload.Id = "_menuItemReload";

			_menuItemFullReload = new MenuItem();
			_menuItemFullReload.Text = "&Full Reload";
			_menuItemFullReload.Id = "_menuItemFullReload";

			var menuSeparator3 = new MenuSeparator();

			_menuItemQuit = new MenuItem();
			_menuItemQuit.Text = "&Quit";
			_menuItemQuit.Id = "_menuItemQuit";

			var menuItem1 = new MenuItem();
			menuItem1.Text = "&File";
			menuItem1.Items.Add(_menuItemOpenFolder);
			menuItem1.Items.Add(_menuItemSaveCurrentItem);
			menuItem1.Items.Add(_menuItemSaveEverything);
			menuItem1.Items.Add(menuSeparator1);
			menuItem1.Items.Add(_menuItemNewPrefab);
			menuItem1.Items.Add(_menuItemNewScene);
			menuItem1.Items.Add(menuSeparator2);
			menuItem1.Items.Add(_menuItemReload);
			menuItem1.Items.Add(_menuItemFullReload);
			menuItem1.Items.Add(menuSeparator3);
			menuItem1.Items.Add(_menuItemQuit);

			_menuItemAbout = new MenuItem();
			_menuItemAbout.Text = "&About";
			_menuItemAbout.Id = "_menuItemAbout";

			var menuItem2 = new MenuItem();
			menuItem2.Text = "&Help";
			menuItem2.Items.Add(_menuItemAbout);

			var horizontalMenu1 = new HorizontalMenu();
			horizontalMenu1.Items.Add(menuItem1);
			horizontalMenu1.Items.Add(menuItem2);

			_panelSceneExplorer = new ScrollViewer();
			_panelSceneExplorer.Id = "_panelSceneExplorer";

			_panelSolution = new ScrollViewer();
			_panelSolution.Id = "_panelSolution";

			_leftSplitPane = new VerticalSplitPane();
			_leftSplitPane.Id = "_leftSplitPane";
			_leftSplitPane.Widgets.Add(_panelSceneExplorer);
			_leftSplitPane.Widgets.Add(_panelSolution);

			var label1 = new Label();
			label1.Text = "Grid";

			_buttonGrid = new ToggleButton();
			_buttonGrid.Id = "_buttonGrid";
			_buttonGrid.Content = label1;

			var label2 = new Label();
			label2.Text = "Render Buffers";

			_buttonVisualizeBuffers = new ToggleButton();
			_buttonVisualizeBuffers.Id = "_buttonVisualizeBuffers";
			_buttonVisualizeBuffers.Content = label2;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_buttonGrid);
			horizontalStackPanel1.Widgets.Add(_buttonVisualizeBuffers);

			var label3 = new Label();
			label3.Text = "Camera View";

			var toggleButton1 = new ToggleButton();
			toggleButton1.Content = label3;

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Left = 2;
			horizontalStackPanel2.Top = 2;
			horizontalStackPanel2.Widgets.Add(toggleButton1);

			var tabItem1 = new TabItem();
			tabItem1.Text = "Test";
			tabItem1.Content = horizontalStackPanel2;

			_tabControlScenes = new TabControl();
			_tabControlScenes.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_tabControlScenes.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_tabControlScenes.CloseableTabs = true;
			_tabControlScenes.Id = "_tabControlScenes";
			_tabControlScenes.Items.Add(tabItem1);

			var label4 = new Label();
			label4.Text = "Effects Switches:";

			var label5 = new Label();
			label5.Text = "Draw Calls:";
			Grid.SetRow(label5, 1);

			var label6 = new Label();
			label6.Text = "Vertices Drawn:";
			Grid.SetRow(label6, 2);

			var label7 = new Label();
			label7.Text = "Primitives Drawn:";
			Grid.SetRow(label7, 3);

			var label8 = new Label();
			label8.Text = "Render Target Switches:";
			Grid.SetRow(label8, 4);

			_labelEffectsSwitches = new Label();
			_labelEffectsSwitches.Text = "10";
			_labelEffectsSwitches.Id = "_labelEffectsSwitches";
			Grid.SetColumn(_labelEffectsSwitches, 1);

			_labelDrawCalls = new Label();
			_labelDrawCalls.Text = "10";
			_labelDrawCalls.Id = "_labelDrawCalls";
			Grid.SetColumn(_labelDrawCalls, 1);
			Grid.SetRow(_labelDrawCalls, 1);

			_labelVerticesDrawn = new Label();
			_labelVerticesDrawn.Text = "10";
			_labelVerticesDrawn.Id = "_labelVerticesDrawn";
			Grid.SetColumn(_labelVerticesDrawn, 1);
			Grid.SetRow(_labelVerticesDrawn, 2);

			_labelPrimitivesDrawn = new Label();
			_labelPrimitivesDrawn.Text = "10";
			_labelPrimitivesDrawn.Id = "_labelPrimitivesDrawn";
			Grid.SetColumn(_labelPrimitivesDrawn, 1);
			Grid.SetRow(_labelPrimitivesDrawn, 3);

			_labelRenderTargetSwitches = new Label();
			_labelRenderTargetSwitches.Text = "10";
			_labelRenderTargetSwitches.Id = "_labelRenderTargetSwitches";
			Grid.SetColumn(_labelRenderTargetSwitches, 1);
			Grid.SetRow(_labelRenderTargetSwitches, 4);

			_panelStatistics = new Grid();
			_panelStatistics.ColumnSpacing = 8;
			_panelStatistics.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_panelStatistics.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_panelStatistics.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_panelStatistics.Left = -4;
			_panelStatistics.Id = "_panelStatistics";
			_panelStatistics.Widgets.Add(label4);
			_panelStatistics.Widgets.Add(label5);
			_panelStatistics.Widgets.Add(label6);
			_panelStatistics.Widgets.Add(label7);
			_panelStatistics.Widgets.Add(label8);
			_panelStatistics.Widgets.Add(_labelEffectsSwitches);
			_panelStatistics.Widgets.Add(_labelDrawCalls);
			_panelStatistics.Widgets.Add(_labelVerticesDrawn);
			_panelStatistics.Widgets.Add(_labelPrimitivesDrawn);
			_panelStatistics.Widgets.Add(_labelRenderTargetSwitches);

			var panel1 = new Panel();
			StackPanel.SetProportionType(panel1, Myra.Graphics2D.UI.ProportionType.Fill);
			panel1.Widgets.Add(_tabControlScenes);
			panel1.Widgets.Add(_panelStatistics);

			_panelScenes = new VerticalStackPanel();
			_panelScenes.Id = "_panelScenes";
			_panelScenes.Widgets.Add(horizontalStackPanel1);
			_panelScenes.Widgets.Add(panel1);

			var panel2 = new Panel();
			panel2.Widgets.Add(_panelScenes);

			_propertyGrid = new PropertyGrid();
			_propertyGrid.Id = "_propertyGrid";

			var scrollViewer1 = new ScrollViewer();
			StackPanel.SetProportionType(scrollViewer1, Myra.Graphics2D.UI.ProportionType.Fill);
			scrollViewer1.Content = _propertyGrid;

			_panelObjectButtons = new HorizontalStackPanel();
			_panelObjectButtons.Spacing = 8;
			_panelObjectButtons.Id = "_panelObjectButtons";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(scrollViewer1);
			verticalStackPanel1.Widgets.Add(_panelObjectButtons);

			_topSplitPane = new HorizontalSplitPane();
			_topSplitPane.Id = "_topSplitPane";
			_topSplitPane.Widgets.Add(_leftSplitPane);
			_topSplitPane.Widgets.Add(panel2);
			_topSplitPane.Widgets.Add(verticalStackPanel1);

			var panel3 = new Panel();
			StackPanel.SetProportionType(panel3, Myra.Graphics2D.UI.ProportionType.Fill);
			panel3.Widgets.Add(_topSplitPane);

			
			Id = "_mainPanel";
			Widgets.Add(horizontalMenu1);
			Widgets.Add(panel3);
		}

		
		public MenuItem _menuItemOpenFolder;
		public MenuItem _menuItemSaveCurrentItem;
		public MenuItem _menuItemSaveEverything;
		public MenuItem _menuItemNewPrefab;
		public MenuItem _menuItemNewScene;
		public MenuItem _menuItemReload;
		public MenuItem _menuItemFullReload;
		public MenuItem _menuItemQuit;
		public MenuItem _menuItemAbout;
		public ScrollViewer _panelSceneExplorer;
		public ScrollViewer _panelSolution;
		public VerticalSplitPane _leftSplitPane;
		public ToggleButton _buttonGrid;
		public ToggleButton _buttonVisualizeBuffers;
		public TabControl _tabControlScenes;
		public Label _labelEffectsSwitches;
		public Label _labelDrawCalls;
		public Label _labelVerticesDrawn;
		public Label _labelPrimitivesDrawn;
		public Label _labelRenderTargetSwitches;
		public Grid _panelStatistics;
		public VerticalStackPanel _panelScenes;
		public PropertyGrid _propertyGrid;
		public HorizontalStackPanel _panelObjectButtons;
		public HorizontalSplitPane _topSplitPane;
	}
}
